# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iTunesMediaDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iTunesMediaDemo
    pod 'ReachabilitySwift'
    pod 'SwiftyJSON'
    pod 'IQKeyboardManagerSwift'
    pod 'NVActivityIndicatorView'
    pod 'Alamofire', '~> 4.4'


end
